name: Godot Checks

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup Godot
        uses: chickensoft-games/setup-godot@v2
        with:
          version: 4.7.1
          use-dotnet: false

      - name: Check Godot project
        run: godot --headless --editor --quit

      - name: Install GDScript Toolkit
        run: pip install "gdtoolkit==4.*"

      - name: Show gdlint help
        run: gdlint --help

      - name: Lint GDScript
        run: gdlint .